feature

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,18 +1,29 @@
 #!/usr/bin/env bash
 # Script which will display info of the subdomain
 
-dns_config () {
-    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
-    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
+dns_config() {
+    local domain="$1"
+    local subdomain="$2"
+
+    local script
+    script=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
+    
+    if [ -z "$script" ]; then
+        echo "Unable to find DNS records for $subdomain.$domain"
+        return 1
+    fi
+
+    echo "$subdomain $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
 }
 
-if [ "$#" == 1 ]
-then
-  dns_config "$1" "www"
-  dns_config "$1" "lb-01"
-  dns_config "$1" "web-01"
-  dns_config "$1" "web-02"
-elif [ "$#" == 2 ]
-then
-  dns_config "$1" "$2"
+# Main entry point
+if [ "$#" -eq 1 ]; then
+    for subdomain in "www" "lb-01" "web-01" "web-02"; do
+        dns_config "$1" "$subdomain"
+    done
+elif [ "$#" -eq 2 ]; then
+    dns_config "$1" "$2"
+else
+    echo "Usage: $0 domain [subdomain]"
+    exit 1
 fi
